repos:
  - repo: https://github.com/psf/black
    rev: b0d1fba7ac3be53c71fb0d3211d911e629f8aecb  # frozen: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: dbf82f2dd09ae41d9355bcd7ab69187a19e6bf2f  # frozen: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile=black"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "9db230353b823e61e76b88bf2272329e3ad32c3a"  # frozen: v0.0.254
    hooks:
      - id: ruff
